apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30001 #abrindo a porta para o mundo externo
  selector:
    app: sistema-noticias

    